---
- hosts: all
  tasks:
    - name: "Instala o PHP7.3"
      apt:
        name: php7.3
        state: latest
      become: yes

    - name: "Instala o Apache2"
      apt:
        name: apache2
        state: latest
      become: yes

    - name: "Instala ModPHP"
      apt:
        name: libapache2-mod-php7.3
      become: yes
