---
- name: "Instala lista de pacotes"
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - mariadb-server
    - python-mysqldb

- name: "Cria o banco MySQL"
  become: yes
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present

- name: "Cria usuario do MySQL"
  become: yes
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - "{{ wp_host_ip }}"

- name: Configurar o MySQL para aceitar conexões remotas
  become: yes
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: "^bind-address.*$"
    line: "bind-address = {{ mysql_bind_address }}"
  notify:
    - Restart Mysql
# Exemplo usando a substituicao do arquivo:
# - name: "Configura MySQL para aceitar conexões remotas"
#   copy:
#     src: "files/my.cnf"
#     dest: "/etc/mysql/my.cnf"
#   become: yes
#   notify:
#     - restart mysql
